### ISSUE TITLE
explore data on pycharm

### ISSUE THREAD

**Issue by KLANJRI** [yemre-data/interactive-covid-19-dashboard#3]
- [x] Upload 3 covid df
- [x] Data wrangling and cleaning
- [x] Introduce myself to the world
- [x] Visualise insights

**Comment by yemre-data** [comment]
We upload data I think

**Comment by KLANJRI** [comment]
@yemre-data we can add 'recovered' df too as advised by tutor

**Comment by yemre-data** [comment]
Yes after finish cleaning we should add final data that we will use for visualization.
