### ISSUE TITLE
Read Me Section

### ISSUE THREAD

**Issue by yemre-data** [yemre-data/interactive-covid-19-dashboard#4]
Hi everyone as you can see I start commit you can see in your pycharm when you make clone. And Can you handle it Read Me section please?

**Comment by LishaLing** [comment]
I wrote something in read me last night, and I'll renew it today, did you see it?

**Comment by yemre-data** [comment]
Yes I saw thank you

**Comment by KLANJRI** [comment]
we need to add a description of how to run streamlit on pycharm

**Comment by yemre-data** [comment]
finished
